version: '3.7'

services:
  php:
    container_name: test-issue-php
    user: 1000:1000
    build:
      context: ./docker/app
    volumes:
      - .:/var/www/app
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      APP_ENV: 'dev'
    ports:
      - 8080:8080
    links:
      - database

  nginx:
    container_name: test-issue-nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./public:/static
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  database:
    container_name: test-issue-db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: slim_project
      MYSQL_USER: webmaster
      MYSQL_PASSWORD: webmaster
